# GitHub workflow action on workflow_dispatch (manual run):
#   In WordPress repository, update readme.txt and/or assets content.
#
# Define SVN_USERNAME, SVN_PASSWORD for wordpress.org credentials
# Organization or Repository : Settings -> Secrets and Variables -> Actions
#
# wordpress.org plugin slug is the repository name (lower case).
# Expects wordpress.org assets (screenshots, icons, banners) to be in /.wp-assets.
#
# See: https://github.com/10up/action-wordpress-plugin-asset-update/
#
# Version: 26.0813.1

name: Plugin asset/readme update
on:
  workflow_dispatch:

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  update:
    name: Push to WP SVN on update
    runs-on: ubuntu-latest
    steps:

    - name: Plugin-Slug
      # SLUG is the lower-case plugin slug/folder name.
      run: |
        echo "SLUG=${REPO_NAME,,}" >>${GITHUB_ENV}

    - name: Checkout-Code
      # checkout the repository code
      uses: actions/checkout@v7

    - name: Plugin-Update
      uses: 10up/action-wordpress-plugin-asset-update@stable
      env:
        ASSETS_DIR: .wp-assets
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
